export const cardData = [
  {
    id: 1,
    field: "프론트엔드 개발자",
    company: "에이팀벤처스",
    location: "서울 · 한국",
    option: "채용 보상금 1,000,000원",
  },
  {
    id: 2,
    field: "프론트엔드 개발자",
    company: "에이팀벤처스",
    location: "서울 · 한국",
    option: "채용 보상금 1,000,000원",
  },
  {
    id: 3,
    field: "프론트엔드 개발자",
    company: "에이팀벤처스",
    location: "서울 · 한국",
    option: "채용 보상금 1,000,000원",
  },
  {
    id: 4,
    field: "프론트엔드 개발자",
    company: "에이팀벤처스",
    location: "서울 · 한국",
    option: "채용 보상금 1,000,000원",
  },
  {
    id: 5,
    field: "프론트엔드 개발자",
    company: "에이팀벤처스",
    location: "서울 · 한국",
    option: "채용 보상금 1,000,000원",
  },
  {
    id: 6,
    field: "프론트엔드 개발자",
    company: "에이팀벤처스",
    location: "서울 · 한국",
    option: "채용 보상금 1,000,000원",
  },
  {
    id: 7,
    field: "프론트엔드 개발자",
    company: "에이팀벤처스",
    location: "서울 · 한국",
    option: "채용 보상금 1,000,000원",
  },
  {
    id: 8,
    field: "프론트엔드 개발자",
    company: "에이팀벤처스",
    location: "서울 · 한국",
    option: "채용 보상금 1,000,000원",
  },
];
